# Generated by Django 5.1.15 on 2026-08-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['kind', 'name'], 'verbose_name_plural': 'categories'},
        ),
    ]
