# Generated by Django 5.1.15 on 2026-08-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_remove_category_unique_category_name_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('SEMI_MONTHLY', 'Semi-monthly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for an Overall budget spanning all expense categories.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_definitions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='budgets.budgetdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('is_archived', False)), fields=('user', 'category', 'scope'), name='unique_active_budget_per_user_category_scope'),
        ),
        migrations.AddConstraint(
            model_name='budgetdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('is_archived', False)), fields=('user', 'scope'), name='unique_active_overall_budget_per_user_scope'),
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.UniqueConstraint(fields=('definition', 'period_start'), name='unique_period_per_definition'),
        ),
    ]
