# Generated by Django 5.1.15 on 2026-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdefinition',
            name='second_half_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semi-monthly only: a different amount for the 16th-end-of-month half. Leave blank to use the same amount as the first half.', max_digits=14, null=True),
        ),
    ]
